# Site settings
title: Nicole C. Whitehead
email: ncwhitehead@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio for the Birmingham, AL developer Nicole Whitehead Johnson.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nwjohn.github.com/" # the base hostname & protocol for your site
twitter_username: nwjohn0
github_username:  ncwjohn

# Build settings
markdown: kramdown
